# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-PDF
version:      0.29
version_from: lib/Text/PDF.pm
installdirs:  vendor
requires:
    Compress::Zlib:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
